[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
adelos_registry = "7T1UxHJ6psKiQheKZXxANu6mhgsmgaX55eNKZZL5u4Rp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
